language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script: vendor/bin/phpunit --coverage-text

notifications:
  email:
    - sk@xbug.de